# Generated by Django 2.0.1 on 2018-01-04 09:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('zero', django.db.models.manager.Manager()),
            ],
        ),
    ]
